#!/usr/bin/env bash
# rules.sh — declarative catalog of KNOWN cleaners with classification metadata.
# Dynamic discovery (discover.sh) handles everything not listed here (Electron
# apps, browsers, unknown caches) so Clinj adapts to each machine.
#
# Each rule: id|category|safe|mode|regen|label|target
#   safe   : safe | aggressive | review
#   mode   : tree (remove path) | contents (empty path) | cmd (PATH::COMMAND)
#   target : a path under $HOME, or for cmd "SIZING_PATH::shell command"
# Paths use ~ which is expanded at discovery time.

clinj_known_rules() {
cat <<'RULES'
npm|dev-js|safe|tree|re-downloaded on next install|npm cache|~/.npm/_cacache
npm-logs|dev-js|safe|tree|recreated on next run|npm logs|~/.npm/_logs
pnpm|dev-js|safe|tree|re-fetched by pnpm store|pnpm store|~/Library/Caches/pnpm
yarn-cache|dev-js|safe|tree|re-downloaded on install|Yarn cache|~/Library/Caches/Yarn
yarn-home|dev-js|safe|tree|re-downloaded on install|Yarn cache (~/.yarn)|~/.yarn/cache
node-gyp|dev-js|safe|tree|rebuilt on native install|node-gyp cache|~/Library/Caches/node-gyp
next-swc|dev-js|safe|tree|rebuilt by Next.js|Next.js swc cache|~/Library/Caches/next-swc
typescript|dev-js|safe|tree|rebuilt by tsc|TypeScript cache|~/Library/Caches/typescript
bun|dev-js|safe|tree|re-downloaded by bun|Bun install cache|~/.bun/install/cache
deno|dev-js|safe|tree|re-fetched by deno|Deno cache|~/Library/Caches/deno
pip|dev-py|safe|tree|re-downloaded by pip|pip cache|~/Library/Caches/pip
uv|dev-py|safe|tree|re-downloaded by uv|uv cache|~/.cache/uv
huggingface|dev-py|review|tree|re-downloaded (can be large models)|HuggingFace cache|~/.cache/huggingface
go-build|dev-native|safe|tree|rebuilt by go|Go build cache|~/Library/Caches/go-build
cargo-cache|dev-native|safe|tree|re-downloaded by cargo|Cargo registry cache|~/.cargo/registry/cache
gradle-caches|dev-native|safe|tree|re-downloaded by Gradle|Gradle caches|~/.gradle/caches
gradle-daemon|dev-native|safe|tree|recreated by Gradle|Gradle daemon logs|~/.gradle/daemon
cocoapods|dev-mobile|aggressive|tree|re-cloned by pod install (slow)|CocoaPods repos|~/.cocoapods/repos
playwright|dev-js|safe|tree|re-downloaded on next test run|Playwright browsers|~/Library/Caches/ms-playwright
playwright-go|dev-js|safe|tree|re-downloaded on next test run|Playwright (Go) browsers|~/Library/Caches/ms-playwright-go
xcode-derived|dev-mobile|safe|tree|rebuilt on next Xcode build|Xcode DerivedData|~/Library/Developer/Xcode/DerivedData
xcode-archives|dev-mobile|aggressive|tree|rebuild to recreate|Xcode Archives|~/Library/Developer/Xcode/Archives
xcode-devsupport|dev-mobile|aggressive|tree|re-fetched on device connect|Xcode iOS DeviceSupport|~/Library/Developer/Xcode/iOS DeviceSupport
coresim-caches|dev-mobile|safe|tree|recreated by Simulator|iOS Simulator caches|~/Library/Developer/CoreSimulator/Caches
xcode-macos-devsupport|dev-mobile|aggressive|tree|re-fetched on device connect|Xcode macOS DeviceSupport|~/Library/Developer/Xcode/macOS DeviceSupport
xcode-watchos-devsupport|dev-mobile|aggressive|tree|re-fetched on device connect|Xcode watchOS DeviceSupport|~/Library/Developer/Xcode/watchOS DeviceSupport
swiftpm|dev-mobile|safe|tree|re-resolved by SwiftPM|SwiftPM cache|~/Library/Caches/org.swift.swiftpm
carthage|dev-mobile|safe|tree|re-built by Carthage|Carthage cache|~/Library/Caches/org.carthage.CarthageKit
dotslash|dev-native|safe|tree|re-downloaded on next use|dotslash cache|~/Library/Caches/dotslash
cargo-cache|dev-native|safe|tree|re-downloaded by cargo|Cargo registry cache|~/.cargo/registry/cache
jetbrains-caches|dev-native|safe|tree|rebuilt by the IDE|JetBrains IDE caches|~/Library/Caches/JetBrains
jetbrains-logs|dev-native|safe|tree|recreated by the IDE|JetBrains logs|~/Library/Logs/JetBrains
pub-cache|dev-native|safe|tree|re-downloaded by pub/Flutter|Dart/Flutter pub cache|~/.pub-cache
brew|dev-native|safe|cmd|re-downloaded on next install|Homebrew cleanup|~/Library/Caches/Homebrew::brew cleanup -s
docker|containers|safe|cmd|dangling layers rebuilt|Docker dangling (>72h)|~/Library/Containers/com.docker.docker::docker system prune -f --filter until=72h
spotify|apps|safe|tree|re-streamed by Spotify|Spotify cache|~/Library/Caches/com.spotify.client
adobe-media|apps|review|tree|rebuilt by Adobe apps|Adobe media cache|~/Library/Application Support/Adobe/Common/Media Cache Files
adobe-cache|apps|safe|tree|rebuilt by Adobe apps|Adobe caches|~/Library/Caches/Adobe
quicklook|system|safe|cmd|regenerated by macOS|QuickLook thumbnails|~/Library/Caches/com.apple.QuickLook.thumbnailcache::qlmanage -r cache
diag-reports|system|safe|tree|regenerated by macOS|Diagnostic reports|~/Library/Logs/DiagnosticReports
trash|trash|safe|contents|—|Empty Trash|~/.Trash
RULES
}
